[package]
name = "reth-rlp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0"
description = "Fast RLP serialization library"
homepage.workspace = true
repository.workspace = true

[dependencies]
arrayvec = { version = "0.7", default-features = false }
auto_impl = "1"
bytes.workspace = true
ethnum = { version = "1", default-features = false, optional = true }
smol_str = { version = "0.2", default-features = false, optional = true }
ethereum-types = { version = "0.14", features = ["codec"], optional = true }
revm-primitives = { workspace = true, features = ["serde"] }
reth-rlp-derive = { path = "./rlp-derive", optional = true }

# for eip-4844
c-kzg = { workspace = true, optional = true }

[dev-dependencies]
reth-rlp = { workspace = true, features = [
    "derive",
    "std",
    "ethnum",
    "ethereum-types",
    "smol_str",
] }
hex-literal.workspace = true
criterion = "0.5.0"
pprof = { version = "0.12", features = ["flamegraph", "frame-pointer", "criterion"] }

[features]
default = ["kzg"]
alloc = []
derive = ["reth-rlp-derive"]
std = ["alloc"]
kzg = ["c-kzg"]

[[bench]]
name = "bench"
harness = false
