[package]
name = "reth-rpc-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Helpers for configuring RPC"

[dependencies]
# reth
reth-primitives.workspace = true
reth-ipc = { path = "../ipc" }
reth-interfaces.workspace = true
reth-network-api.workspace = true
reth-provider.workspace = true
reth-rpc = { path = "../rpc" }
reth-rpc-api = { path = "../rpc-api" }
reth-rpc-engine-api = { path = "../rpc-engine-api" }
reth-rpc-types.workspace = true
reth-tasks.workspace = true
reth-transaction-pool.workspace = true
reth-rpc-types-compat.workspace = true

# rpc/net
jsonrpsee = { workspace = true, features = ["server"] }
tower-http = { version = "0.4", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
hyper = "0.14"

# metrics
reth-metrics = { workspace = true, features = ["common"] }
metrics.workspace = true

# misc
strum = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
reth-tracing = { path = "../../tracing" }
reth-rpc-api = { path = "../rpc-api", features = ["client"] }
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-network-api.workspace = true
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth-beacon-consensus = { path = "../../consensus/beacon" }
reth-payload-builder = { workspace = true, features = ["test-utils"] }

tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
serde_json.workspace = true
