[package]
name = "reth-trie"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Merkle trie implementation
"""

[dependencies]
# reth
reth-primitives.workspace = true
reth-interfaces.workspace = true
reth-rlp.workspace = true
reth-db = { path = "../storage/db" }

# tokio
tokio = { workspace = true, default-features = false, features = ["sync"] }

# tracing
tracing.workspace = true

# misc 
hex = "0.4"
thiserror.workspace = true
derive_more = "0.99"

# test-utils
triehash = { version = "0.8", optional = true }

[dev-dependencies]
# reth
reth-primitives = { workspace = true, features = ["test-utils", "arbitrary"] }
reth-db = { path = "../storage/db", features = ["test-utils"] }
reth-provider.workspace = true

# trie
triehash = "0.8"

# misc
proptest.workspace = true
tokio = { workspace = true, default-features = false, features = ["sync", "rt", "macros"] }
tokio-stream.workspace = true
criterion = "0.5"
pretty_assertions = "1.3.0"

[features]
test-utils = ["triehash"]

[[bench]]
name = "prefix_set"
harness = false
